### ISSUE TITLE
关于 Segue几种类型的区别 中的一个问题

### ISSUE THREAD

**Issue by imzyf** [pro648/tips#1]
请问 show(_, sender:) 与 navigationController?.pushViewController 是什么关系？有什么异同？

**Comment by pro648** [comment]
`showViewController:sender:`方法为视图控制器提供了自适应（adaptive）、灵活的呈现方式。该方法让presenting view controller决定如何呈现视图控制器。例如：容器视图控制器会以子视图控制器的形式呈现新的控制器，而非默认的modal形式。`showViewController:sender:`也是首选使用的方法。

`pushViewController:animated:`只能用在导航控制器堆栈中，不能用在`UIViewController`实例。在storyboar中，push segue已不推荐使用。

所以，推荐使用`showViewController:sender:`。查看[这篇文章](https://github.com/pro648/tips/wiki/View%20Controller%20%E8%BD%AC%E5%9C%BA)了解更为详细介绍。

**Comment by imzyf** [comment]
thanks. 

> show和push用在导航堆栈视图控制器时没有区别。在storyboar中，push segue已不推荐使用。所以，如果你不需要支持iOS 7，应当使用自适应性强、Apple推荐的showViewController: sender:、showDetailViewController: sender:方法。
