### ISSUE TITLE
iOS 正则表达式语法全集中的勘误

### ISSUE THREAD

**Issue by Andy0570** [pro648/tips#2]
该文章中有两点需要指正的地方，以免误导读者。

`\w` 匹配包括下划线的任何单词字符。等价于 `[a-zA-Z0-9_]`。
`\W` 匹配任何非单词字符。等价于 `[^a-zA-Z0-9_]`。

等价表达式中少了下划线（`_`）。

**Comment by cc617703015** [comment]
？？？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;独木舟的木&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月9日(星期二) 上午10:13
收件人:&nbsp;&quot;pro648/tips&quot;<tips@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[pro648/tips] iOS 正则表达式语法全集中的勘误 (#2)

**Comment by pro648** [comment]
特别感谢指出文章中的错误之处，已经更正了。
